apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


bases:
- ../../base/app1
- ../../base/app2

commonLabels:
  env: staging

namespace: staging

resources:
  - namespace.yaml

patchesStrategicMerge:
  - ./app1/deployment.yaml
  - ./app2/deployment.yaml