apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


bases:
- ../../base/app1
- ../../base/app2

commonLabels:
  env: production

namespace: production

patchesStrategicMerge:
  - ./app1/deployment.yaml
  - ./app2/deployment.yaml